import json

path = r'D:\OpenCodeNLLM\OpenCode\Transformer_Notebooks\transformer_learning\notebooks\15_final_end_to_end.ipynb'
with open(path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

cells = nb['cells']

for i, cell in enumerate(cells):
    if cell['cell_type'] != 'code':
        continue

    new_lines = None

    if i == 1:  # imports — remove logging
        new_lines = [
            "# Импорты: стандартная библиотека, PyTorch, sklearn, вспомогательные утилиты",
            "import sys, os, math, json",
            "",
            "import torch",
            "import torch.nn as nn",
            "import torch.nn.functional as F",
            "import numpy as np",
            "import matplotlib.pyplot as plt",
            "from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay",
            "from collections import Counter",
            "",
            "# Автоопределение устройства: CUDA > MPS > CPU",
            "if torch.cuda.is_available():",
            "    device = torch.device('cuda')",
            "elif torch.backends.mps.is_available():",
            "    device = torch.device('mps')",
            "else:",
            "    device = torch.device('cpu')",
            "",
        ]

    elif i == 3:  # dataset loading
        new_lines = [
            "",
            "# Загружаем IMDB: 200 train (100 pos + 100 neg), 100 test (50+50)",
            "from datasets import load_dataset",
            "",
            "dataset = load_dataset('stanfordnlp/imdb', split=['train[:100]+train[-100:]', 'test[:50]+test[-50:]'])",
            "train_data, test_data = dataset",
            "",
            "print(f'Train: {len(train_data)} samples')",
            "print(f'Test:  {len(test_data)} samples')",
            "print(f'Pos review: {sum(train_data[\"label\"])} / {len(train_data)}')",
            "",
        ]

    elif i == 5:  # vocabulary and encoding
        new_lines = [
            "",
            "# Специальные токены: BOS, EOS, PAD, UNK",
            "BOS, EOS, PAD, UNK = 0, 1, 2, 3",
            "max_vocab_size = 100  # ограничиваем словарь для скорости",
            "max_len = 200  # макс. длина последовательности",
            "",
            "# Строим словарь символов на тренировочных данных",
            "char_counts = Counter()",
            "for text in train_data['text']:",
            "    char_counts.update(text.lower()[:500])  # берём начало каждого отзыва",
            "",
            "most_common = char_counts.most_common(max_vocab_size - 4)",
            "vocab = {ch: idx+4 for idx, (ch, _) in enumerate(most_common)}  # резервируем 0-3",
            "vocab_size = len(vocab) + 4",
            "print(f'Vocabulary size: {vocab_size}')",
            "print(f'Most common chars: {[ch for ch, _ in most_common[:15]]}')",
            "",
            "def encode(text):",
            "    # Преобразует текст в последовательность ID: BOS + символы + EOS + PAD",
            "    tokens = [BOS]",
            "    for ch in text.lower()[:max_len-2]:",
            "        tokens.append(vocab.get(ch, UNK))  # неизвестные символы -> UNK",
            "    tokens.append(EOS)",
            "    tokens = tokens + [PAD] * (max_len - len(tokens))  # дополняем до max_len",
            "    return tokens[:max_len]",
            "",
            "train_ids = torch.tensor([encode(t) for t in train_data['text']])",
            "train_labels = torch.tensor(train_data['label'])",
            "test_ids = torch.tensor([encode(t) for t in test_data['text']])",
            "test_labels = torch.tensor(test_data['label'])",
            "",
            "print(f'Train tensor: {train_ids.shape}')",
            "print(f'Test tensor:  {test_ids.shape}')",
            "",
        ]

    elif i == 7:  # TransformerClassifier — remove log.info
        new_lines = [
            "",
            "class TransformerClassifier(nn.Module):",
            "    def __init__(self, vocab_size, d_model=64, n_heads=4, num_layers=4, num_classes=2, max_len=200, dropout=0.1):",
            "        super().__init__()",
            "        self.d_model = d_model",
            "        # Таблица эмбеддингов с поддержкой PAD-токена (не обучается для padding_idx)",
            "        self.embedding = nn.Embedding(vocab_size, d_model, padding_idx=PAD)",
            "        ",
            "        # Синусоидальные позиционные кодирования",
            "        pe = torch.zeros(max_len, d_model)",
            "        position = torch.arange(0, max_len).float().unsqueeze(1)",
            "        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))",
            "        pe[:, 0::2] = torch.sin(position * div_term)",
            "        pe[:, 1::2] = torch.cos(position * div_term)",
            "        self.register_buffer('pe', pe.unsqueeze(0))",
            "        ",
            "        # Стандартный TransformerEncoder от PyTorch (batch_first=True)",
            "        encoder_layer = nn.TransformerEncoderLayer(d_model, n_heads, 4*d_model, dropout, activation='gelu', batch_first=True)",
            "        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers)",
            "        ",
            "        # Классификационная голова: [CLS] -> d_model -> классы",
            "        self.classifier = nn.Sequential(",
            "            nn.Linear(d_model, d_model),",
            "            nn.GELU(),",
            "            nn.Dropout(dropout),",
            "            nn.Linear(d_model, num_classes),",
            "        )",
            "    ",
            "    def forward(self, x, mask=None):",
            "        if mask is None:",
            "            key_pad_mask = (x == PAD)  # маска PAD из raw token IDs",
            "        else:",
            "            key_pad_mask = mask",
            "        # Эмбеддинг + позиционное кодирование + TransformerEncoder",
            "        x = self.embedding(x) * math.sqrt(self.d_model) + self.pe[:, :x.size(1), :]",
            "        x = self.encoder(x, src_key_padding_mask=key_pad_mask)",
            "        cls_output = x[:, 0, :]  # берём выход первого токена [BOS] как CLS",
            "        return self.classifier(cls_output)",
            "",
            "classifier = TransformerClassifier(",
            "    vocab_size=vocab_size, d_model=32, n_heads=4, num_layers=3, max_len=max_len",
            ").to(device)",
            "print(f'Model params: {sum(p.numel() for p in classifier.parameters()):,}')",
        ]

    elif i == 9:  # training loop
        new_lines = [
            "",
            "criterion = nn.CrossEntropyLoss()",
            "optimizer = torch.optim.AdamW(classifier.parameters(), lr=0.001, weight_decay=0.01)",
            "",
            "n_epochs = 30",
            "batch_size = 16",
            "train_losses, val_accs = [], []  # логи для графика",
            "",
            "for epoch in range(n_epochs):",
            "    classifier.train()",
            "    epoch_loss = 0",
            "    perm = torch.randperm(len(train_ids))  # перемешиваем на каждой эпохе",
            "    ",
            "    # Мини-батч: forward + loss + backward + optimizer",
            "    for i in range(0, len(train_ids), batch_size):",
            "        idx = perm[i:i+batch_size]",
            "        inputs = train_ids[idx].to(device)",
            "        labels = train_labels[idx].to(device)",
            "        ",
            "        output = classifier(inputs)",
            "        loss = criterion(output, labels)",
            "        ",
            "        optimizer.zero_grad()",
            "        loss.backward()",
            "        optimizer.step()",
            "        epoch_loss += loss.item()",
            "    ",
            "    # Валидация после каждой эпохи",
            "    classifier.eval()",
            "    all_preds, all_true = [], []",
            "    with torch.no_grad():",
            "        for i in range(0, len(test_ids), batch_size):",
            "            inputs = test_ids[i:i+batch_size].to(device)",
            "            labels = test_labels[i:i+batch_size]",
            "            output = classifier(inputs)",
            "            preds = output.argmax(-1).cpu()",
            "            all_preds.extend(preds.tolist())",
            "            all_true.extend(labels.tolist())",
            "    ",
            "    acc = accuracy_score(all_true, all_preds)",
            "    avg_loss = epoch_loss / (len(train_ids) / batch_size)",
            "    train_losses.append(avg_loss)",
            "    val_accs.append(acc)",
            "    ",
            "    # Печать каждые 10 эпох для отслеживания прогресса",
            "    if epoch % 10 == 0:",
            "",
            "# Графики: loss и accuracy по эпохам",
            "fig, axes = plt.subplots(1, 2, figsize=(12, 4))",
            "axes[0].plot(train_losses)",
            "axes[0].set_xlabel('Epoch')",
            "axes[0].set_ylabel('Loss')",
            "axes[0].set_title('Training Loss')",
            "axes[0].grid(True)",
            "",
            "axes[1].plot(val_accs)",
            "axes[1].set_xlabel('Epoch')",
            "axes[1].set_ylabel('Accuracy')",
            "axes[1].set_title('Validation Accuracy')",
            "axes[1].grid(True)",
            "plt.tight_layout()",
            "plt.show()",
            "",
        ]

    elif i == 11:  # final evaluation
        new_lines = [
            "",
            "# Финальная оценка: accuracy, F1 и матрица ошибок",
            "classifier.eval()",
            "all_preds, all_true = [], []",
            "with torch.no_grad():",
            "    for i in range(0, len(test_ids), batch_size):",
            "        inputs = test_ids[i:i+batch_size].to(device)",
            "        labels = test_labels[i:i+batch_size]",
            "        output = classifier(inputs)",
            "        all_preds.extend(output.argmax(-1).cpu().tolist())",
            "        all_true.extend(labels.tolist())",
            "",
            "acc = accuracy_score(all_true, all_preds)",
            "f1 = f1_score(all_true, all_preds)",
            "cm = confusion_matrix(all_true, all_preds, labels=[0, 1])",
            "",
            "print(f'Accuracy:  {acc:.2%}')",
            "print(f'F1 Score:  {f1:.4f}')",
            "print(f'Confusion Matrix:')",
            "print(cm)",
            "",
            "# Визуализация матрицы ошибок",
            "fig, ax = plt.subplots(figsize=(5, 4))",
            "ConfusionMatrixDisplay(cm, display_labels=['Negative', 'Positive']).plot(ax=ax)",
            "plt.title('Confusion Matrix: Our Transformer')",
            "plt.tight_layout()",
            "plt.show()",
            "",
        ]

    elif i == 13:  # comparison with HuggingFace
        new_lines = [
            "",
            "# Сравнение с предобученным DistilBERT от HuggingFace",
            "from transformers import AutoTokenizer, AutoModelForSequenceClassification",
            "",
            "hf_tokenizer = AutoTokenizer.from_pretrained('distilbert-base-uncased')",
            "hf_model = AutoModelForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=2).to(device)",
            "",
            "# Прогоняем те же тестовые данные через DistilBERT",
            "hf_preds = []",
            "for text in test_data['text']:",
            "    inputs = hf_tokenizer(text, return_tensors='pt', truncation=True, max_length=256).to(device)",
            "    with torch.no_grad():",
            "        output = hf_model(**inputs)",
            "    hf_preds.append(output.logits.argmax(-1).item())",
            "",
            "hf_acc = accuracy_score(test_labels, hf_preds)",
            "hf_f1 = f1_score(test_labels, hf_preds)",
            "",
            "# Печать сравнительной таблицы",
            "print('=' * 50)",
            "print(f\"{'Model':30s} {'Accuracy':>10s} {'F1':>10s}\")",
            "print('-' * 50)",
            "print(f\"{'Our Transformer (scratch)':30s} {acc:>9.2%} {f1:>10.4f}\")",
            "print(f\"{'DistilBERT (pretrained)':30s} {hf_acc:>9.2%} {hf_f1:>10.4f}\")",
            "print('=' * 50)",
            "print(f'\\nOur params: {sum(p.numel() for p in classifier.parameters()):,}')",
            "print(f'DistilBERT params: {sum(p.numel() for p in hf_model.parameters()):,}')",
            "",
        ]

    elif i == 15:  # summary
        new_lines = [
            "# Итоговый вывод — финальные метрики обеих моделей",
            "print('=== Final End-to-End Complete ===')",
            "print(f'Our Transformer:  Acc={acc:.2%}, F1={f1:.4f}, params={sum(p.numel() for p in classifier.parameters()):,}')",
            "print(f'DistilBERT:       Acc={hf_acc:.2%}, F1={hf_f1:.4f}, params={sum(p.numel() for p in hf_model.parameters()):,}')",
            "print('\\nAll 15 notebooks complete!')",
            "",
        ]

    if new_lines is not None:
        cell['source'] = [l + '\n' for l in new_lines]

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print("Notebook 15 done")
